package com.together.utils



const val NOTIFICATION_CHANNEL_ID = "order_channel"
const val NOTIFICATION_CHANNEL_NAME = "Bestellungen"
const val NOTIFICATION_ID = 1

const val ACTION_SHOW_ORDER_FRAGMENT = "ACTION_SHOW_ORDER_FRAGMENT"
const val ACTION_START_SERVICE = "ACTION_START_SERVICE"
const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"